server:
  port: 7070

spring:
  profiles:
    active: prod
  application:
    name: oc-auth
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: lin:8848
        username: nacos
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: lin
      port: 27017
      database: ocean
      username: root
      password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

oc-logging:
  path: ../logs/
  filename: oc-auth
  packagename: com.lmk

mybatis-plus:
  mapper-locations: classpath*:com/lmk/auth/*/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDelete