server:
  port: 7070

oc-logging:
  path: ../logs/
  filename: oc-gateway
  packagename: com.lmk

spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: oc-gateway
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: lin:8848
        username: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oc-auth-service
          uri: lb://oc-auth
          predicates:
            - Path=/oc-auth/**
          filters:
            - StripPrefix=1
        - id: oc-conf-service
          uri: lb://oc-conf
          predicates:
            - Path=/oc-conf/**
          filters:
            - StripPrefix=1


